#!/bin/sh

dir="$(dirname "$0")"

parallel_1 () {
  "$dir/test_schema"
  "$dir/test_kotlin"
}
parallel_2 () {
  "$dir/test_python"
}
parallel_3 () {
  "$dir/test_rust"

  cd rust
  cargo +stable test || { echo "FAIL RUST STABLE"; exit 1; }
  cd ..
}

parallel_1 &
parallel_2 &
parallel_3 &

wait
