#!/bin/sh

dir="$(dirname "$0")"

cd "$dir/../rust/"

cargo --color=always test -- --color=always || { echo "FAIL RUST"; exit 1; }
cargo --color=always fmt --check || { echo "FAIL FMT"; exit 1; }
cargo --color=always clippy --no-deps -- -D warnings || { echo "FAIL CLIPPY"; exit 1; }
cargo --color=always test --benches -- --color=always || { echo "FAIL BENCHES"; exit 1; }
trunk build || { echo "FAIL TRUNK"; exit 1; }

cd -