#!/bin/sh

dir="$(dirname "$0")"

cd "$dir/../rust/"

cargo test || { echo "FAIL RUST"; exit 1; }
cargo fmt --check || { echo "FAIL FMT"; exit 1; }
cargo clippy --no-deps -- -D warnings || { echo "FAIL CLIPPY"; exit 1; }

cd -