#!/bin/sh

dir="$(dirname "$0")"

cd "$dir/../rust/"

cargo --color=always test -- --color=always || { echo "FAIL RUST"; exit 1; }
cargo --color=always fmt --check -- --color=always || { echo "FAIL FMT"; exit 1; }
cargo --color=always clippy --no-deps -- --color=always -D warnings || { echo "FAIL CLIPPY"; exit 1; }

cd -