[package]
name = "osm2lanes"
version = "0.1.0"
edition = "2021"
authors = ["Dustin Carlino <dabreegster@gmail.com>", "Michael Droogleever Fortuyn <droogmic@gmail.com>"]
license = "Apache 2.0"

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11", optional = true, features = ["blocking", "json"] }

[features]
overpass = ["reqwest", "reqwest/blocking", "reqwest/json"]

[dev-dependencies]
serde_yaml = "0.8"
