[package]
name = "osm2lanes"
version = "0.1.0"
edition = "2021"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]


[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
