#!/bin/sh

# Spec.

python data/test_spec.py || { echo "FAIL"; exit 1; }

# Python.

black --check python || { echo "FAIL"; exit 1; }
pytest || { echo "FAIL"; exit 1; }

# Rust.

cd rust
cargo test || { echo "FAIL"; exit 1; }
cargo +nightly fmt --check || { echo "FAIL"; exit 1; }
cargo clippy || { echo "FAIL"; exit 1; }
cd ..

# Kotlin.

ktlint || { echo "FAIL"; exit 1; }
cd kotlin
gradle clean
gradle test || { echo "FAIL"; exit 1; }
cd ..

exit 0
