#!/bin/sh

# Python.

pytest -v || { echo "FAIL"; exit 1; }

# Rust.

cd rust/osm2lanes
cargo test || { echo "FAIL"; exit 1; }
cd ../..

# Kotlin.

cd kotlin
gradle clean
gradle test || { echo "FAIL"; exit 1; }
cd ..

exit 0
