name: "Deploy osm-tags Crate"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: CARGO_REGISTRY_TOKEN
      url: https://crates.io/
    strategy:
      matrix:
        crate: ["osm-tags"]
    steps:
      - uses: actions/checkout@v2
      - name: "Publish ${{ matrix.crate }}"
        run: |
          rustup toolchain install stable
          rustup override set stable
          cd ${{ matrix.crate }}
          cargo package --list
          cargo publish
