name: 'deploy osm-tags crate'

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "publish osm-tags"
        run: |
          rustup toolchain install stable
          rustup override set stable
          cd osm-tags/
          cargo publish --dry-run
