name: Deploy crate

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "publish osm2lanes"
        run: |
          rustup toolchain install stable
          rustup override set stable
          cd osm2lanes/
          cargo publish --dry-run
