name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Setup Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip
    - name: "Install Dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
    - name: "Test Schema"
      run: sh .githooks/test_schema
    - name: "Test Python"
      run: sh .githooks/test_python

  kotlin:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Setup Kotlin"
      uses: fwilhe2/setup-kotlin@main
    - name: "Setup Ktlint"
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.43.2/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
    # START: For YAML to JSON conversion, TODO: remove
    - name: "Setup Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip
    - name: "Generate Test JSON"
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
        sh .githooks/test_schema
    # END
    - name: "Test Kotlin"
      run: sh .githooks/test_kotlin

  # Moved away from actions-rs because of
  # https://github.com/actions-rs/cargo/pull/59#issuecomment-1012974186
  rust:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Cache"
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust
    - name: "Test Rust"
      run: |
        sh .githooks/test_rust
    - uses: boa-dev/criterion-compare-action@v3.2.0
      with:
        cwd: "rust"
        benchName: "benchmark_tests"
        branchName: ${{ github.base_ref }}
  
  rust-stable:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Rustup"
      run: |
        cd ./rust/
        rustup toolchain install stable
        rustup override set stable
    - name: "Cache"
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust
    - name: "Test Rust"
      run: |
        cd ./rust/
        rustup show
        cargo test
