name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Setup Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip
    - name: "Install Dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
    - name: "Test Schema"
      run: test_schema
    - name: "Test Python"
      run: test_python

  kotlin:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Setup Kotlin"
      uses: fwilhe2/setup-kotlin@main
    # START: For YAML to JSON conversion, TODO: remove
    - name: "Setup Python 3.9"
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: pip
    - name: "Generate Test JSON"
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
        test_schema
    # END
    - name: "Test Kotlin"
      run: test_kotlin

  # Moved away from actions-rs because of
  # https://github.com/actions-rs/cargo/pull/59#issuecomment-1012974186
  rust:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Cache"
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust
    - name: Run cargo fmt
      run: |
        cd rust
        rustup show
        cd -
        test_rust
  
  rust-stable:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: "Rustup"
      run: |
        cd ./rust/
        rustup toolchain install stable
        rustup override set stable
    - name: "Cache"
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust
    - name: "Test"
      run: |
        cd ./rust/
        rustup show
        cargo test
