name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
    - name: Test the schema
      run: python data/test_spec.py
    - name: Test the Python implementation
      run: pytest -v

  kotlin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Kotlin
      uses: fwilhe2/setup-kotlin@main
    # START: For YAML to JSON conversion
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
    - name: Test the schema
      run: python data/test_spec.py
    # END
    - name: Test the Kotlin implementation
      run: |
        cd kotlin
        gradle test

  # TODO, find a better action: https://github.com/actions-rs/cargo/issues/6
  # move away from actions-rs because of https://github.com/actions-rs/cargo/pull/59#issuecomment-1012974186
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: actions-rs/toolchain@v1
      with:
        # waiting for https://github.com/actions-rs/toolchain/pull/209
        # and rust/rust-toolchain.toml
        toolchain: nightly-2022-02-03
        profile: default
        override: true
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path rust/Cargo.toml
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path rust/Cargo.toml --check
        working-directory: ./rust
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --manifest-path rust/Cargo.toml -- -D warnings
        working-directory: ./rust
  rust-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      uses: actions-rs/cargo@v1
      with:
        toolchain: stable
        command: test
        args: --manifest-path rust/Cargo.toml
        working-directory: ./rust
