name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Python

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
    - name: Test the schema
      run: python data/test_spec.py
    - name: Test the Python implementation
      run: pytest -v

    # Rust

    - name: Install Rust stable
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Install Rust nightly
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - name: Test the Rust implementation
      run: |
        cd rust/osm2lanes
        cargo test
        cargo +nightly fmt --check
        cargo clippy

    # Kotlin

    - name: Set up Kotlin
      uses: fwilhe2/setup-kotlin@main
    - name: Test the Kotlin implementation
      run: |
        cd kotlin
        gradle test
