name: "Deploy Web"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0

      - name: Build web app
        run: trunk --config Release.toml build

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Build lane editor app
        run: |
          cd web_editor
          wasm-pack build --release --target web ../osm2lanes-npm
          # Make a full copy of what we'll publish, dereferencing symlinks
          mkdir editor
          cp -RLv assets/ js/ *.html *.css editor
          # wasm-pack generates this file, but it'll prevent the action below from working
          rm -fv editor/js/osm2lanes-npm/.gitignore
          mv editor ../dist

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
